### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  自定义函数的错误代码。 错误代码将显示在调用函数的单元格中。


  除了这些错误代码之外，还将显示自定义错误消息。 自定义邮件显示在错误指示器菜单中，该菜单通过将鼠标悬停在包含错误的每个单元格上的错误标志上方来访问。
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 此错误代码指示使用的函数被零或空单元格除。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 此错误代码指示函数名称中有拼写错误。 请注意，此错误代码支持为自定义函数输入错误，而不是作为自定义函数输出错误。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 此错误代码指示函数中的某个数字存在问题。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 此错误代码指示函数引用了无效的单元格。 请注意，此错误代码支持为自定义函数输入错误，而不是作为自定义函数输出错误。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 此错误代码指示函数中的值的数据类型错误。 如果需要，除了错误代码之外，还可以使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 此错误代码指示函数或服务不可用。 如果需要，除了错误代码之外，还可以使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 此错误代码指示函数中的区域不相交。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: cec80f674bc573e3e3d3679ab96792ea5e469ce3
  ms.sourcegitcommit: a6ecbc9abca2ab5c82af4c869e3e2d72c999a4c1
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "49538399"
